title: "Wanderer"
baseURL: "https://mnezerka.github.io/wanderer/"
languageCode: "en"
defaultContentLanguage: "en"

enableMissingTranslationPlaceholders: true

pagination.pageSize: 3

capitalizeListTitles: false

theme: wanderer
themesDir:  "../.."

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: -1

outputFormats:
  MediaIndex:
    baseName: mediaindex
    isPlainText: true
    mediaType: application/json
    notAlternative: true

outputs:
  home:
    - html
    - json
    - MediaIndex

params:
  author: Wanderer
#  titleColor: green
  titleSuffix: Demo Site
#  titleSuffixColor: red
  poweredBy: Powered by <a href='http://www.gohugo.io/'>Hugo</a>
  mapyCzApiKey: "XuWC4G9t0QFM3t-Ra5iKyxc54dal-3wsHFNTGsI04Ew"
  mapClustering: "no"
